# Generated by Django 4.2.5 on 2023-09-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_drive_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='folder',
            field=models.FileField(upload_to='Folder'),
        ),
    ]
